name: forcast collector

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  run_challenge:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
        
    - name: Verify the MD5 against the script file.
      run: md5sum -c md5sum.txt
      
    - name: Execute the script.
      run: |
        pip3 install beautifulsoup4
        python3 forcast_collector.py
      
    - name: Archive forcast_data.json
      uses: actions/upload-artifact@v3
      with:
        name: forcast_data.json
        path: forcast_data.json
